name: Android Build

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version name aplikasi (contoh: 1.0.1)"
        required: true
        default: "1.0.0"

      upload_release:
        description: "Upload ke GitHub Release?"
        required: true
        type: choice
        default: "false"
        options:
          - "false"
          - "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set App Version
        run: |
          sed -i "s/versionName \".*\"/versionName \"${{ github.event.inputs.version_name }}\"/" app/build.gradle

      - name: Build Release APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      - name: Upload GitHub Release
        if: ${{ github.event.inputs.upload_release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version_name }}
          files: app/build/outputs/apk/release/*.apk
